# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
import baml_py

from . import stream_types, types, type_builder
from .parser import LlmResponseParser, LlmStreamParser
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME as __runtime__


class BamlAsyncClient:
    __options: DoNotUseDirectlyCallManager
    __stream_client: "BamlStreamClient"
    __http_request: "BamlHttpRequestClient"
    __http_stream_request: "BamlHttpStreamRequestClient"
    __llm_response_parser: LlmResponseParser
    __llm_stream_parser: LlmStreamParser

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options
        self.__stream_client = BamlStreamClient(options)
        self.__http_request = BamlHttpRequestClient(options)
        self.__http_stream_request = BamlHttpStreamRequestClient(options)
        self.__llm_response_parser = LlmResponseParser(options)
        self.__llm_stream_parser = LlmStreamParser(options)

    def with_options(self,
        tb: typing.Optional[type_builder.TypeBuilder] = None,
        client_registry: typing.Optional[baml_py.baml_py.ClientRegistry] = None,
        client: typing.Optional[str] = None,
        collector: typing.Optional[typing.Union[baml_py.baml_py.Collector, typing.List[baml_py.baml_py.Collector]]] = None,
        env: typing.Optional[typing.Dict[str, typing.Optional[str]]] = None,
        tags: typing.Optional[typing.Dict[str, str]] = None,
        on_tick: typing.Optional[typing.Callable[[str, baml_py.baml_py.FunctionLog], None]] = None,
    ) -> "BamlAsyncClient":
        options: BamlCallOptions = {}
        if tb is not None:
            options["tb"] = tb
        if client_registry is not None:
            options["client_registry"] = client_registry
        if client is not None:
            options["client"] = client
        if collector is not None:
            options["collector"] = collector
        if env is not None:
            options["env"] = env
        if tags is not None:
            options["tags"] = tags
        if on_tick is not None:
            options["on_tick"] = on_tick
        return BamlAsyncClient(self.__options.merge_options(options))

    @property
    def stream(self):
      return self.__stream_client

    @property
    def request(self):
      return self.__http_request

    @property
    def stream_request(self):
      return self.__http_stream_request

    @property
    def parse(self):
      return self.__llm_response_parser

    @property
    def parse_stream(self):
      return self.__llm_stream_parser

    async def ExtractAcupuncture(self, source_context: str,
        baml_options: BamlCallOptions = {},
    ) -> types.AcupunctureProtocol:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.ExtractAcupuncture(source_context=source_context,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="ExtractAcupuncture", args={
                "source_context": source_context,
            })
            return typing.cast(types.AcupunctureProtocol, __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def ExtractClinicalOutcomes(self, source_context: str,
        baml_options: BamlCallOptions = {},
    ) -> types.OutcomeExtraction:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.ExtractClinicalOutcomes(source_context=source_context,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="ExtractClinicalOutcomes", args={
                "source_context": source_context,
            })
            return typing.cast(types.OutcomeExtraction, __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def ExtractMetadata(self, source_context: str,
        baml_options: BamlCallOptions = {},
    ) -> types.MetadataExtraction:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.ExtractMetadata(source_context=source_context,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="ExtractMetadata", args={
                "source_context": source_context,
            })
            return typing.cast(types.MetadataExtraction, __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def ExtractRiskOfBias(self, source_context: str,
        baml_options: BamlCallOptions = {},
    ) -> types.RiskOfBiasExtraction:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.ExtractRiskOfBias(source_context=source_context,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="ExtractRiskOfBias", args={
                "source_context": source_context,
            })
            return typing.cast(types.RiskOfBiasExtraction, __result__.cast_to(types, types, stream_types, False, __runtime__))
    


class BamlStreamClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ExtractAcupuncture(self, source_context: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.AcupunctureProtocol, types.AcupunctureProtocol]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="ExtractAcupuncture", args={
            "source_context": source_context,
        })
        return baml_py.BamlStream[stream_types.AcupunctureProtocol, types.AcupunctureProtocol](
          __result__,
          lambda x: typing.cast(stream_types.AcupunctureProtocol, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.AcupunctureProtocol, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def ExtractClinicalOutcomes(self, source_context: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.OutcomeExtraction, types.OutcomeExtraction]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="ExtractClinicalOutcomes", args={
            "source_context": source_context,
        })
        return baml_py.BamlStream[stream_types.OutcomeExtraction, types.OutcomeExtraction](
          __result__,
          lambda x: typing.cast(stream_types.OutcomeExtraction, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.OutcomeExtraction, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def ExtractMetadata(self, source_context: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.MetadataExtraction, types.MetadataExtraction]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="ExtractMetadata", args={
            "source_context": source_context,
        })
        return baml_py.BamlStream[stream_types.MetadataExtraction, types.MetadataExtraction](
          __result__,
          lambda x: typing.cast(stream_types.MetadataExtraction, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.MetadataExtraction, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def ExtractRiskOfBias(self, source_context: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.RiskOfBiasExtraction, types.RiskOfBiasExtraction]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="ExtractRiskOfBias", args={
            "source_context": source_context,
        })
        return baml_py.BamlStream[stream_types.RiskOfBiasExtraction, types.RiskOfBiasExtraction](
          __result__,
          lambda x: typing.cast(stream_types.RiskOfBiasExtraction, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.RiskOfBiasExtraction, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    

class BamlHttpRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    async def ExtractAcupuncture(self, source_context: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ExtractAcupuncture", args={
            "source_context": source_context,
        }, mode="request")
        return __result__
    async def ExtractClinicalOutcomes(self, source_context: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ExtractClinicalOutcomes", args={
            "source_context": source_context,
        }, mode="request")
        return __result__
    async def ExtractMetadata(self, source_context: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ExtractMetadata", args={
            "source_context": source_context,
        }, mode="request")
        return __result__
    async def ExtractRiskOfBias(self, source_context: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ExtractRiskOfBias", args={
            "source_context": source_context,
        }, mode="request")
        return __result__
    

class BamlHttpStreamRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    async def ExtractAcupuncture(self, source_context: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ExtractAcupuncture", args={
            "source_context": source_context,
        }, mode="stream")
        return __result__
    async def ExtractClinicalOutcomes(self, source_context: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ExtractClinicalOutcomes", args={
            "source_context": source_context,
        }, mode="stream")
        return __result__
    async def ExtractMetadata(self, source_context: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ExtractMetadata", args={
            "source_context": source_context,
        }, mode="stream")
        return __result__
    async def ExtractRiskOfBias(self, source_context: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ExtractRiskOfBias", args={
            "source_context": source_context,
        }, mode="stream")
        return __result__
    

b = BamlAsyncClient(DoNotUseDirectlyCallManager({}))