# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions


from . import stream_types, types
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions

class LlmResponseParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ExtractAcupuncture(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.AcupunctureProtocol:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractAcupuncture", llm_response=llm_response, mode="request")
        return typing.cast(types.AcupunctureProtocol, __result__)

    def ExtractClinicalOutcomes(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.OutcomeExtraction:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractClinicalOutcomes", llm_response=llm_response, mode="request")
        return typing.cast(types.OutcomeExtraction, __result__)

    def ExtractMetadata(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.MetadataExtraction:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractMetadata", llm_response=llm_response, mode="request")
        return typing.cast(types.MetadataExtraction, __result__)

    def ExtractRiskOfBias(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.RiskOfBiasExtraction:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractRiskOfBias", llm_response=llm_response, mode="request")
        return typing.cast(types.RiskOfBiasExtraction, __result__)

    

class LlmStreamParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ExtractAcupuncture(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.AcupunctureProtocol:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractAcupuncture", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.AcupunctureProtocol, __result__)

    def ExtractClinicalOutcomes(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.OutcomeExtraction:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractClinicalOutcomes", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.OutcomeExtraction, __result__)

    def ExtractMetadata(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.MetadataExtraction:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractMetadata", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.MetadataExtraction, __result__)

    def ExtractRiskOfBias(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.RiskOfBiasExtraction:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractRiskOfBias", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.RiskOfBiasExtraction, __result__)

    