# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict, Field

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (8)
# #########################################################################

class AcupunctureProtocol(BaseModel):
    control_type_transformed: typing.Optional[int] = None
    control_type_components: typing.List[int]
    acupuncture_type: typing.Optional[int] = None
    stimulation_type: typing.Optional[int] = None
    point_selection_scheme: typing.Optional[int] = None
    treatment_frequency_raw: typing.Optional[str] = None
    treatment_frequency_value: typing.Optional[float] = None
    treatment_frequency_unit: typing.Optional[int] = None
    treatment_duration_raw: typing.Optional[str] = None
    treatment_duration_value: typing.Optional[float] = None
    treatment_duration_unit: typing.Optional[int] = None
    total_sessions: typing.Optional[int] = None
    deqi: typing.Optional[int] = None
    needle_depth_raw: typing.Optional[str] = None
    retention_time_raw: typing.Optional[str] = None
    retention_time_value: typing.Optional[float] = None
    practitioner_experience_years: typing.Optional[float] = None
    practitioner_experience_raw: typing.Optional[str] = None
    practitioner_experience_comparator: typing.Optional[str] = None
    evidence: typing.List["EvidenceQuote"]

class Arm(BaseModel):
    arm_id: typing.Optional[str] = None
    arm_label: typing.Optional[str] = None
    role: typing.Optional[str] = None
    n: typing.Optional[int] = None
    estimate: typing.Optional[float] = None
    lower: typing.Optional[float] = None
    upper: typing.Optional[float] = None
    event_count: typing.Optional[int] = None

class ClinicalOutcome(BaseModel):
    table_id: typing.Optional[str] = None
    row_id: typing.Optional[str] = None
    outcome_name: typing.Optional[str] = None
    measurement_instrument: typing.Optional[str] = None
    outcome_observation_timepoint_raw: typing.Optional[str] = None
    outcome_observation_timepoint_value: typing.Optional[float] = None
    outcome_observation_timepoint_unit: typing.Optional[int] = None
    statistic_type: typing.Optional[str] = None
    analysis_population: typing.Optional[str] = None
    intervention_estimate: typing.Optional[float] = None
    intervention_variance_lower: typing.Optional[float] = None
    intervention_variance_upper: typing.Optional[float] = None
    intervention_n: typing.Optional[int] = None
    control_estimate: typing.Optional[float] = None
    control_variance_lower: typing.Optional[float] = None
    control_variance_upper: typing.Optional[float] = None
    control_n: typing.Optional[int] = None
    between_group_measure: typing.Optional[str] = None
    outcome_between_group_estimate: typing.Optional[float] = None
    outcome_between_group_lower: typing.Optional[float] = None
    outcome_between_group_upper: typing.Optional[float] = None
    outcome_p_value: typing.Optional[float] = None
    outcome_p_value_comparator: typing.Optional[str] = None
    effect_size_name: typing.Optional[str] = None
    arm: typing.List["Arm"]
    comparison: typing.Optional["Comparison"] = None
    analysis_set: typing.Optional[str] = None
    record_role: typing.Optional[str] = None
    evidence: typing.List["EvidenceQuote"]

class Comparison(BaseModel):
    relation: typing.Optional[str] = None
    intervention_arm_id: typing.Optional[str] = None
    control_arm_id: typing.Optional[str] = None
    comparator_arm_ids: typing.List[str]
    contrast: typing.Optional[str] = None

class EvidenceQuote(BaseModel):
    field_id: typing.Optional[str] = None
    quote: typing.Optional[str] = None
    page: typing.Optional[int] = None
    source: typing.Optional[types.EvidenceSource] = None
    support_type: typing.Optional[types.EvidenceSupportType] = None
    derivation: typing.Optional[str] = None

class MetadataExtraction(BaseModel):
    title: typing.Optional[str] = None
    publication_year: typing.Optional[int] = None
    language: typing.Optional[str] = None
    journal: typing.Optional[str] = None
    first_author: typing.Optional[str] = None
    author_contact: typing.Optional[str] = None
    disease_name: typing.Optional[str] = None
    country: typing.Optional[str] = None
    intervention: typing.Optional[str] = None
    control: typing.Optional[str] = None
    evidence: typing.List["EvidenceQuote"]

class OutcomeExtraction(BaseModel):
    outcomes: typing.List["ClinicalOutcome"]

class RiskOfBiasExtraction(BaseModel):
    random_sequence_method: typing.Optional[str] = None
    random_sequence_class: typing.Optional[int] = None
    allocation_concealment: typing.Optional[str] = None
    allocation_concealment_class: typing.Optional[int] = None
    participant_blinding: typing.Optional[int] = None
    outcome_assessor_blinding: typing.Optional[int] = None
    randomized_sample_intervention_raw: typing.Optional[int] = None
    randomized_sample_control_raw: typing.Optional[int] = None
    total_randomized: typing.Optional[int] = None
    primary_analysis: typing.Optional[int] = None
    missing_data_method: typing.Optional[int] = None
    evidence: typing.List["EvidenceQuote"]

# #########################################################################
# Generated type aliases (0)
# #########################################################################


# #########################################################################
# Model rebuilds (8)
# #########################################################################
# Resolve string forward references now that every model above is defined so
# class declaration order never breaks Pydantic construction (issue #793).
# Recursive models are intentionally omitted (Pydantic resolves those lazily;
# eagerly rebuilding them can recurse).
AcupunctureProtocol.model_rebuild()
Arm.model_rebuild()
ClinicalOutcome.model_rebuild()
Comparison.model_rebuild()
EvidenceQuote.model_rebuild()
MetadataExtraction.model_rebuild()
OutcomeExtraction.model_rebuild()
RiskOfBiasExtraction.model_rebuild()
