# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict, Field


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (2)
# #########################################################################

class EvidenceSource(str, Enum):
    Markdown = "Markdown"
    Table = "Table"
    Figure = "Figure"
    Crossref = "Crossref"

class EvidenceSupportType(str, Enum):
    Direct = "Direct"
    Derived = "Derived"

# #########################################################################
# Generated classes (8)
# #########################################################################

class AcupunctureProtocol(BaseModel):
    control_type_transformed: typing.Optional[int] = None
    control_type_components: typing.List[int]
    acupuncture_type: typing.Optional[int] = None
    stimulation_type: typing.Optional[int] = None
    point_selection_scheme: typing.Optional[int] = None
    treatment_frequency_raw: str
    treatment_frequency_value: typing.Optional[float] = None
    treatment_frequency_unit: typing.Optional[int] = None
    treatment_duration_raw: str
    treatment_duration_value: typing.Optional[float] = None
    treatment_duration_unit: typing.Optional[int] = None
    total_sessions: typing.Optional[int] = None
    deqi: int
    needle_depth_raw: str
    retention_time_raw: str
    retention_time_value: typing.Optional[float] = None
    practitioner_experience_years: typing.Optional[float] = None
    practitioner_experience_raw: str
    practitioner_experience_comparator: str
    evidence: typing.List["EvidenceQuote"]

class Arm(BaseModel):
    arm_id: str
    arm_label: str
    role: str
    n: typing.Optional[int] = None
    estimate: typing.Optional[float] = None
    lower: typing.Optional[float] = None
    upper: typing.Optional[float] = None
    event_count: typing.Optional[int] = None

class ClinicalOutcome(BaseModel):
    table_id: str
    row_id: str
    outcome_name: str
    measurement_instrument: str
    outcome_observation_timepoint_raw: str
    outcome_observation_timepoint_value: typing.Optional[float] = None
    outcome_observation_timepoint_unit: typing.Optional[int] = None
    statistic_type: str
    analysis_population: str
    intervention_estimate: typing.Optional[float] = None
    intervention_variance_lower: typing.Optional[float] = None
    intervention_variance_upper: typing.Optional[float] = None
    intervention_n: typing.Optional[int] = None
    control_estimate: typing.Optional[float] = None
    control_variance_lower: typing.Optional[float] = None
    control_variance_upper: typing.Optional[float] = None
    control_n: typing.Optional[int] = None
    between_group_measure: str
    outcome_between_group_estimate: typing.Optional[float] = None
    outcome_between_group_lower: typing.Optional[float] = None
    outcome_between_group_upper: typing.Optional[float] = None
    outcome_p_value: typing.Optional[float] = None
    outcome_p_value_comparator: str
    effect_size_name: str
    arm: typing.List["Arm"]
    comparison: "Comparison"
    analysis_set: str
    record_role: str
    evidence: typing.List["EvidenceQuote"]

class Comparison(BaseModel):
    relation: str
    intervention_arm_id: str
    control_arm_id: str
    comparator_arm_ids: typing.List[str]
    contrast: str

class EvidenceQuote(BaseModel):
    field_id: str
    quote: str
    page: typing.Optional[int] = None
    source: EvidenceSource
    support_type: EvidenceSupportType
    derivation: typing.Optional[str] = None

class MetadataExtraction(BaseModel):
    title: str
    publication_year: typing.Optional[int] = None
    language: str
    journal: str
    first_author: str
    author_contact: str
    disease_name: str
    country: str
    intervention: str
    control: str
    evidence: typing.List["EvidenceQuote"]

class OutcomeExtraction(BaseModel):
    outcomes: typing.List["ClinicalOutcome"]

class RiskOfBiasExtraction(BaseModel):
    random_sequence_method: str
    random_sequence_class: int
    allocation_concealment: str
    allocation_concealment_class: int
    participant_blinding: int
    outcome_assessor_blinding: int
    randomized_sample_intervention_raw: typing.Optional[int] = None
    randomized_sample_control_raw: typing.Optional[int] = None
    total_randomized: typing.Optional[int] = None
    primary_analysis: int
    missing_data_method: int
    evidence: typing.List["EvidenceQuote"]

# #########################################################################
# Generated type aliases (0)
# #########################################################################


# #########################################################################
# Model rebuilds (8)
# #########################################################################
# Resolve string forward references now that every model above is defined so
# class declaration order never breaks Pydantic construction (issue #793).
# Recursive models are intentionally omitted (Pydantic resolves those lazily;
# eagerly rebuilding them can recurse).
AcupunctureProtocol.model_rebuild()
Arm.model_rebuild()
ClinicalOutcome.model_rebuild()
Comparison.model_rebuild()
EvidenceQuote.model_rebuild()
MetadataExtraction.model_rebuild()
OutcomeExtraction.model_rebuild()
RiskOfBiasExtraction.model_rebuild()
