# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
from baml_py import type_builder
from baml_py import baml_py
# These are exports, not used here, hence the linter is disabled
from baml_py.baml_py import FieldType, EnumValueBuilder, EnumBuilder, ClassBuilder # noqa: F401 # pylint: disable=unused-import
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME

class TypeBuilder(type_builder.TypeBuilder):
    def __init__(self):
        super().__init__(classes=set(
          ["AcupunctureProtocol","Arm","ClinicalOutcome","Comparison","EvidenceQuote","MetadataExtraction","OutcomeExtraction","RiskOfBiasExtraction",]
        ), enums=set(
          ["EvidenceSource","EvidenceSupportType",]
        ), runtime=DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME)

    # #########################################################################
    # Generated enums 2
    # #########################################################################

    @property
    def EvidenceSource(self) -> "EvidenceSourceViewer":
        return EvidenceSourceViewer(self)

    @property
    def EvidenceSupportType(self) -> "EvidenceSupportTypeViewer":
        return EvidenceSupportTypeViewer(self)


    # #########################################################################
    # Generated classes 8
    # #########################################################################

    @property
    def AcupunctureProtocol(self) -> "AcupunctureProtocolViewer":
        return AcupunctureProtocolViewer(self)

    @property
    def Arm(self) -> "ArmViewer":
        return ArmViewer(self)

    @property
    def ClinicalOutcome(self) -> "ClinicalOutcomeViewer":
        return ClinicalOutcomeViewer(self)

    @property
    def Comparison(self) -> "ComparisonViewer":
        return ComparisonViewer(self)

    @property
    def EvidenceQuote(self) -> "EvidenceQuoteViewer":
        return EvidenceQuoteViewer(self)

    @property
    def MetadataExtraction(self) -> "MetadataExtractionViewer":
        return MetadataExtractionViewer(self)

    @property
    def OutcomeExtraction(self) -> "OutcomeExtractionViewer":
        return OutcomeExtractionViewer(self)

    @property
    def RiskOfBiasExtraction(self) -> "RiskOfBiasExtractionViewer":
        return RiskOfBiasExtractionViewer(self)



# #########################################################################
# Generated enums 2
# #########################################################################

class EvidenceSourceAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.enum("EvidenceSource")
        self._values: typing.Set[str] = set([  "Markdown",  "Table",  "Figure",  "Crossref",  ])
        self._vals = EvidenceSourceValues(self._bldr, self._values)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def values(self) -> "EvidenceSourceValues":
        return self._vals


class EvidenceSourceViewer(EvidenceSourceAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_values(self) -> typing.List[typing.Tuple[str, type_builder.EnumValueViewer]]:
        return [(name, type_builder.EnumValueViewer(self._bldr.value(name))) for name in self._values]
    

class EvidenceSourceValues:
    def __init__(self, enum_bldr: baml_py.EnumBuilder, values: typing.Set[str]):
        self.__bldr = enum_bldr
        self.__values = values # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def Markdown(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("Markdown"))
    
    @property
    def Table(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("Table"))
    
    @property
    def Figure(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("Figure"))
    
    @property
    def Crossref(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("Crossref"))
    
    


class EvidenceSupportTypeAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.enum("EvidenceSupportType")
        self._values: typing.Set[str] = set([  "Direct",  "Derived",  ])
        self._vals = EvidenceSupportTypeValues(self._bldr, self._values)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def values(self) -> "EvidenceSupportTypeValues":
        return self._vals


class EvidenceSupportTypeViewer(EvidenceSupportTypeAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_values(self) -> typing.List[typing.Tuple[str, type_builder.EnumValueViewer]]:
        return [(name, type_builder.EnumValueViewer(self._bldr.value(name))) for name in self._values]
    

class EvidenceSupportTypeValues:
    def __init__(self, enum_bldr: baml_py.EnumBuilder, values: typing.Set[str]):
        self.__bldr = enum_bldr
        self.__values = values # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def Direct(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("Direct"))
    
    @property
    def Derived(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("Derived"))
    
    



# #########################################################################
# Generated classes 8
# #########################################################################

class AcupunctureProtocolAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("AcupunctureProtocol")
        self._properties: typing.Set[str] = set([  "control_type_transformed",  "control_type_components",  "acupuncture_type",  "stimulation_type",  "point_selection_scheme",  "treatment_frequency_raw",  "treatment_frequency_value",  "treatment_frequency_unit",  "treatment_duration_raw",  "treatment_duration_value",  "treatment_duration_unit",  "total_sessions",  "deqi",  "needle_depth_raw",  "retention_time_raw",  "retention_time_value",  "practitioner_experience_years",  "practitioner_experience_raw",  "practitioner_experience_comparator",  "evidence",  ])
        self._props = AcupunctureProtocolProperties(self._bldr, self._properties)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "AcupunctureProtocolProperties":
        return self._props


class AcupunctureProtocolViewer(AcupunctureProtocolAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, type_builder.ClassPropertyViewer]]:
        return [(name, type_builder.ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]
    


class AcupunctureProtocolProperties:
    def __init__(self, bldr: baml_py.ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def control_type_transformed(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("control_type_transformed"))
    
    @property
    def control_type_components(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("control_type_components"))
    
    @property
    def acupuncture_type(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("acupuncture_type"))
    
    @property
    def stimulation_type(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("stimulation_type"))
    
    @property
    def point_selection_scheme(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("point_selection_scheme"))
    
    @property
    def treatment_frequency_raw(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("treatment_frequency_raw"))
    
    @property
    def treatment_frequency_value(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("treatment_frequency_value"))
    
    @property
    def treatment_frequency_unit(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("treatment_frequency_unit"))
    
    @property
    def treatment_duration_raw(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("treatment_duration_raw"))
    
    @property
    def treatment_duration_value(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("treatment_duration_value"))
    
    @property
    def treatment_duration_unit(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("treatment_duration_unit"))
    
    @property
    def total_sessions(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("total_sessions"))
    
    @property
    def deqi(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("deqi"))
    
    @property
    def needle_depth_raw(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("needle_depth_raw"))
    
    @property
    def retention_time_raw(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("retention_time_raw"))
    
    @property
    def retention_time_value(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("retention_time_value"))
    
    @property
    def practitioner_experience_years(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("practitioner_experience_years"))
    
    @property
    def practitioner_experience_raw(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("practitioner_experience_raw"))
    
    @property
    def practitioner_experience_comparator(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("practitioner_experience_comparator"))
    
    @property
    def evidence(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("evidence"))
    
    


class ArmAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("Arm")
        self._properties: typing.Set[str] = set([  "arm_id",  "arm_label",  "role",  "n",  "estimate",  "lower",  "upper",  "event_count",  ])
        self._props = ArmProperties(self._bldr, self._properties)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "ArmProperties":
        return self._props


class ArmViewer(ArmAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, type_builder.ClassPropertyViewer]]:
        return [(name, type_builder.ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]
    


class ArmProperties:
    def __init__(self, bldr: baml_py.ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def arm_id(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("arm_id"))
    
    @property
    def arm_label(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("arm_label"))
    
    @property
    def role(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("role"))
    
    @property
    def n(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("n"))
    
    @property
    def estimate(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("estimate"))
    
    @property
    def lower(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("lower"))
    
    @property
    def upper(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("upper"))
    
    @property
    def event_count(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("event_count"))
    
    


class ClinicalOutcomeAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("ClinicalOutcome")
        self._properties: typing.Set[str] = set([  "table_id",  "row_id",  "outcome_name",  "measurement_instrument",  "outcome_observation_timepoint_raw",  "outcome_observation_timepoint_value",  "outcome_observation_timepoint_unit",  "statistic_type",  "analysis_population",  "intervention_estimate",  "intervention_variance_lower",  "intervention_variance_upper",  "intervention_n",  "control_estimate",  "control_variance_lower",  "control_variance_upper",  "control_n",  "between_group_measure",  "outcome_between_group_estimate",  "outcome_between_group_lower",  "outcome_between_group_upper",  "outcome_p_value",  "outcome_p_value_comparator",  "effect_size_name",  "arm",  "comparison",  "analysis_set",  "record_role",  "evidence",  ])
        self._props = ClinicalOutcomeProperties(self._bldr, self._properties)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "ClinicalOutcomeProperties":
        return self._props


class ClinicalOutcomeViewer(ClinicalOutcomeAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, type_builder.ClassPropertyViewer]]:
        return [(name, type_builder.ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]
    


class ClinicalOutcomeProperties:
    def __init__(self, bldr: baml_py.ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def table_id(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("table_id"))
    
    @property
    def row_id(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("row_id"))
    
    @property
    def outcome_name(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("outcome_name"))
    
    @property
    def measurement_instrument(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("measurement_instrument"))
    
    @property
    def outcome_observation_timepoint_raw(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("outcome_observation_timepoint_raw"))
    
    @property
    def outcome_observation_timepoint_value(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("outcome_observation_timepoint_value"))
    
    @property
    def outcome_observation_timepoint_unit(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("outcome_observation_timepoint_unit"))
    
    @property
    def statistic_type(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("statistic_type"))
    
    @property
    def analysis_population(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("analysis_population"))
    
    @property
    def intervention_estimate(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("intervention_estimate"))
    
    @property
    def intervention_variance_lower(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("intervention_variance_lower"))
    
    @property
    def intervention_variance_upper(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("intervention_variance_upper"))
    
    @property
    def intervention_n(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("intervention_n"))
    
    @property
    def control_estimate(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("control_estimate"))
    
    @property
    def control_variance_lower(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("control_variance_lower"))
    
    @property
    def control_variance_upper(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("control_variance_upper"))
    
    @property
    def control_n(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("control_n"))
    
    @property
    def between_group_measure(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("between_group_measure"))
    
    @property
    def outcome_between_group_estimate(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("outcome_between_group_estimate"))
    
    @property
    def outcome_between_group_lower(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("outcome_between_group_lower"))
    
    @property
    def outcome_between_group_upper(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("outcome_between_group_upper"))
    
    @property
    def outcome_p_value(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("outcome_p_value"))
    
    @property
    def outcome_p_value_comparator(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("outcome_p_value_comparator"))
    
    @property
    def effect_size_name(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("effect_size_name"))
    
    @property
    def arm(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("arm"))
    
    @property
    def comparison(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("comparison"))
    
    @property
    def analysis_set(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("analysis_set"))
    
    @property
    def record_role(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("record_role"))
    
    @property
    def evidence(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("evidence"))
    
    


class ComparisonAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("Comparison")
        self._properties: typing.Set[str] = set([  "relation",  "intervention_arm_id",  "control_arm_id",  "comparator_arm_ids",  "contrast",  ])
        self._props = ComparisonProperties(self._bldr, self._properties)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "ComparisonProperties":
        return self._props


class ComparisonViewer(ComparisonAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, type_builder.ClassPropertyViewer]]:
        return [(name, type_builder.ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]
    


class ComparisonProperties:
    def __init__(self, bldr: baml_py.ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def relation(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("relation"))
    
    @property
    def intervention_arm_id(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("intervention_arm_id"))
    
    @property
    def control_arm_id(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("control_arm_id"))
    
    @property
    def comparator_arm_ids(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("comparator_arm_ids"))
    
    @property
    def contrast(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("contrast"))
    
    


class EvidenceQuoteAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("EvidenceQuote")
        self._properties: typing.Set[str] = set([  "field_id",  "quote",  "page",  "source",  "support_type",  "derivation",  ])
        self._props = EvidenceQuoteProperties(self._bldr, self._properties)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "EvidenceQuoteProperties":
        return self._props


class EvidenceQuoteViewer(EvidenceQuoteAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, type_builder.ClassPropertyViewer]]:
        return [(name, type_builder.ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]
    


class EvidenceQuoteProperties:
    def __init__(self, bldr: baml_py.ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def field_id(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("field_id"))
    
    @property
    def quote(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("quote"))
    
    @property
    def page(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("page"))
    
    @property
    def source(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("source"))
    
    @property
    def support_type(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("support_type"))
    
    @property
    def derivation(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("derivation"))
    
    


class MetadataExtractionAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("MetadataExtraction")
        self._properties: typing.Set[str] = set([  "title",  "publication_year",  "language",  "journal",  "first_author",  "author_contact",  "disease_name",  "country",  "intervention",  "control",  "evidence",  ])
        self._props = MetadataExtractionProperties(self._bldr, self._properties)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "MetadataExtractionProperties":
        return self._props


class MetadataExtractionViewer(MetadataExtractionAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, type_builder.ClassPropertyViewer]]:
        return [(name, type_builder.ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]
    


class MetadataExtractionProperties:
    def __init__(self, bldr: baml_py.ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def title(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("title"))
    
    @property
    def publication_year(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("publication_year"))
    
    @property
    def language(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("language"))
    
    @property
    def journal(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("journal"))
    
    @property
    def first_author(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("first_author"))
    
    @property
    def author_contact(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("author_contact"))
    
    @property
    def disease_name(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("disease_name"))
    
    @property
    def country(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("country"))
    
    @property
    def intervention(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("intervention"))
    
    @property
    def control(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("control"))
    
    @property
    def evidence(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("evidence"))
    
    


class OutcomeExtractionAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("OutcomeExtraction")
        self._properties: typing.Set[str] = set([  "outcomes",  ])
        self._props = OutcomeExtractionProperties(self._bldr, self._properties)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "OutcomeExtractionProperties":
        return self._props


class OutcomeExtractionViewer(OutcomeExtractionAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, type_builder.ClassPropertyViewer]]:
        return [(name, type_builder.ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]
    


class OutcomeExtractionProperties:
    def __init__(self, bldr: baml_py.ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def outcomes(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("outcomes"))
    
    


class RiskOfBiasExtractionAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("RiskOfBiasExtraction")
        self._properties: typing.Set[str] = set([  "random_sequence_method",  "random_sequence_class",  "allocation_concealment",  "allocation_concealment_class",  "participant_blinding",  "outcome_assessor_blinding",  "randomized_sample_intervention_raw",  "randomized_sample_control_raw",  "total_randomized",  "primary_analysis",  "missing_data_method",  "evidence",  ])
        self._props = RiskOfBiasExtractionProperties(self._bldr, self._properties)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "RiskOfBiasExtractionProperties":
        return self._props


class RiskOfBiasExtractionViewer(RiskOfBiasExtractionAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, type_builder.ClassPropertyViewer]]:
        return [(name, type_builder.ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]
    


class RiskOfBiasExtractionProperties:
    def __init__(self, bldr: baml_py.ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def random_sequence_method(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("random_sequence_method"))
    
    @property
    def random_sequence_class(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("random_sequence_class"))
    
    @property
    def allocation_concealment(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("allocation_concealment"))
    
    @property
    def allocation_concealment_class(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("allocation_concealment_class"))
    
    @property
    def participant_blinding(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("participant_blinding"))
    
    @property
    def outcome_assessor_blinding(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("outcome_assessor_blinding"))
    
    @property
    def randomized_sample_intervention_raw(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("randomized_sample_intervention_raw"))
    
    @property
    def randomized_sample_control_raw(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("randomized_sample_control_raw"))
    
    @property
    def total_randomized(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("total_randomized"))
    
    @property
    def primary_analysis(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("primary_analysis"))
    
    @property
    def missing_data_method(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("missing_data_method"))
    
    @property
    def evidence(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("evidence"))
    
    

