# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.AcupunctureProtocol": types.AcupunctureProtocol,
    "stream_types.AcupunctureProtocol": stream_types.AcupunctureProtocol,

    "types.Arm": types.Arm,
    "stream_types.Arm": stream_types.Arm,

    "types.ClinicalOutcome": types.ClinicalOutcome,
    "stream_types.ClinicalOutcome": stream_types.ClinicalOutcome,

    "types.Comparison": types.Comparison,
    "stream_types.Comparison": stream_types.Comparison,

    "types.EvidenceQuote": types.EvidenceQuote,
    "stream_types.EvidenceQuote": stream_types.EvidenceQuote,

    "types.MetadataExtraction": types.MetadataExtraction,
    "stream_types.MetadataExtraction": stream_types.MetadataExtraction,

    "types.OutcomeExtraction": types.OutcomeExtraction,
    "stream_types.OutcomeExtraction": stream_types.OutcomeExtraction,

    "types.RiskOfBiasExtraction": types.RiskOfBiasExtraction,
    "stream_types.RiskOfBiasExtraction": stream_types.RiskOfBiasExtraction,


    "types.EvidenceSource": types.EvidenceSource,

    "types.EvidenceSupportType": types.EvidenceSupportType,

}